### ISSUE TITLE
jared我的账号被封了

### ISSUE THREAD

**Issue by MY10282** [jared2021-cn/EP3I#2]
我在消息栏发太多消息被封了
![Minecraft 1 18 1 2022_1_16 3_21_27](https://user-images.githubusercontent.com/97806450/149635763-87dbaa9a-84bd-4d88-9c92-d3a561e6124d.png)

**Comment by jared2021-cn** [comment]
好的，了解，今天解封

**Comment by MY10282** [comment]
什么时候解封啊，现在还没解
